### ISSUE TITLE
Enforce components to be logic-free

### ISSUE THREAD

**Issue by musjj** [Keyslam/Concord#63]
Maybe a bit of a small nitpick, but since components are supposed to be just data, wouldn't it be nicer to enforce it to be logic-free?
Instead of:
```lua
Concord.component("position", function(c, x, y)
    c.x = x or 0
    c.y = y or 0
end)
```
We can do it like this:
```lua
Concord.component("position", { x = 0, y = 0})
```
Of course we can just be *careful* enough to not introduce unwanted logic in components, but I feel that it would be nicer if it it was enforced in the library-level.
What do you think? Any disadvantages with this approach?

**Comment by pablomayobre** [comment]
The function in the component constructor is called an initializer, or a populate function. It's there to help you fill the values your component needs, for example you could load an image, or do some calculation on the arguments. Think of it as a transformation function. It should not modify the state of the World, but only the values of the component itself.

Declaring a component as a table has a bunch of downsides like the need to deep copy the table, something that is not very performant on Lua. It also makes it so that setting different values for the properties becomes more complicated.

Concord encourages users of the library to add logic to their components in multiple places like the initializer, the serialize/deserialize functions, and you can also define methods for the component.
These are all in order to help you use the component in an intuitive way, as if it was a value, this logic you can add should be focused on modifying or getting values from inside your component, they shouldn't modify the state of the World or interact with the entity at all unless that behaviour is evident in its use.

Also ECS is an abstraction, not something Concord tries to enforce as a rule or constraint. Using Concord will feel better if you follow all these recommendations, and you will for sure find less pitfalls if you work in the way Concord was intended.
