### ISSUE TITLE
Loading a namespace of systems with "systems/xyz/init.lua" systems only seems to work if xyz is three characters

### ISSUE THREAD

**Issue by wolfboyft** [Keyslam/Concord#65]
For a directory system called `rendering`: `Error: lib/concord/utils.lua:40: module 'systems.rende' not found`
For a directory system called `map`, it works fine.
Also calling `rendering` `ren` works fine, but `re` doesn't (`module 'systems.r' not found`)

**Comment by pablomayobre** [comment]
What branch are you using (main, dev or experimental) ?

**Comment by wolfboyft** [comment]
main, my install says 3.0

**Comment by Ulhar** [comment]
After testing the code further, I think I've figured out why the bug manifests in this particular way. See, when string.sub receives a negative bound, it will take that as indexing from the end. It will probably be easier to explain with examples:
- We will use bounds of `1` and `#str - 4` here, as those are the bounds used in the code
- `str = "xy"`: 1, -2 -> "x"
- `str = "xyz"`: 1, -1 -> "xyz" (this happens to match the input exactly, which is why this case works in practice)
- `str = xyza`: 1, 0 -> "" (empty string)
It doesn't encounter the possibility of negative end bounds for .lua files since the minimum length of a filename for a .lua is five chars (i.e. `x.lua`), but for subdirectories you can have as low as 1 char. Thus, checking for file type before trimming the name should make sure the negative-end-bound edge case doesn't come up.
